baseurl             = ""
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "zh-CN"
hasCJKLanguage 	    = true
layoutdir           = "layouts"
publishdir          = "public"
theme               = "pixyll"
author              = "Zheng Luo"
title               = "int main() { return 0; }"
pygmentsuseclasses  = true
disqusshortname     = "htfy96blog" # Comment out to disable Disqus.
pluralizelisttitles = false
pygmentsCodeFencesGuessSyntax = true

[permalinks]
blog  = "blog/:slug/"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  # search_engine = false
  twitter_username = "HTwood96"
  disqus_shortname = "htfy96-blog"
  paginate = 5
